model:
  base_learning_rate: 1.0e-05
  target: models.free3d.Free3DDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image_target"
    cond_stage_key: "image_cond"
    image_size: 32
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: hybrid #crossattn #
    monitor: train/loss
    scale_factor: 0.18215

    scheduler_config: # 10000 warmup steps
      target: utils.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 100 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: modules.diffusionmodules.openaimodel.UNetModel
      params:
        views: 1
        use_3d_transformer: False
        use_ray_conditional: True
        use_skel_conditional: True
        use_global_conditional: True
        use_graph_skel: True
        image_size: 16 # unused
        in_channels: 8 #368 #32 #16 #20 # 26
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: modules.encoders.modules.FrozenCLIPImageEmbedder

    ray_embedding_config:
      target: utils.camera.HarmonicEmbedding
      params:
        n_harmonic_functions: 6
        omega_0: 1.0
        append_input: True
    

data:
  target: datasets.DataModuleFromConfig
  params:
    dataname: objaverse_skel_graph
    root_dir: '/objaverse/'
    batch_size: 32
    num_workers: 4
    debug: False
    train:
      total_view: 12
      load_view: 8
      validation: False

    validation:
      total_view: 12
      load_view: 8
      validation: True


lightning:
  find_unused_parameters: false
  metrics_over_trainsteps_checkpoint: false

  logger:
    target: pytorch_lightning.loggers.WandbLogger
    params:
      name: Wandblogger
      project: free3d

  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      verbose: True
      save_last: True
      every_n_train_steps: 200
      save_weights_only: True
      save_on_train_epoch_end: True 
      save_top_k: -1

  callbacks:
    image_logger:
      target: utils.logger.ImageLogger
      params:
        batch_frequency: 500
        max_images: 32
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: False
          inpaint: True
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 32
          ddim_steps: 50
          ddim_eta: 0.0
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  trainer:
    benchmark: True
    limit_test_batches: 0.0
    num_sanity_val_steps: 0
    accumulate_grad_batches: 2